# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
                ('activity_checkin', models.DateTimeField()),
                ('activity_checkout', models.DateTimeField()),
            ],
            options={
                'db_table': 'student_activities',
                'managed': False,
            },
        ),
    ]
